export const LOGIN_USER = 'login_user';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SIGNUP_STUDENTS = 'SIGNUP_STUDENTS';
export const FETCH_SIGNUP_STUDENTS_ERROR = 'FETCH_SIGNUP_STUDENTS_ERROR';
export const FETCH_SIGNUP_STUDENTS_SUCCESS = 'FETCH_SIGNUP_STUDENTS_SUCCESS';
export const FETCH_SIGNUP_STUDENTS_START = 'FETCH_SIGNUP_STUDENTS_START';
