export const LOGIN_USER = 'login_user';
export const SET_LANGUAGE = 'SET_LANGUAGE';

export const FETCH_SIGNUP_ERROR = 'FETCH_SIGNUP_ERROR';
export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS';
export const FETCH_SIGNUP_START = 'FETCH_SIGNUP_START';

export const SIGNUP_DATA_PARAENT = 'SIGNUP_DATA_PARAENT';
export const SIGNUP_DATA_PARAENT_ADD_STUDENT =
  'SIGNUP_DATA_PARAENT_ADD_STUDENT';

export const SIGNUP_DATA_STUDENT = 'SIGNUP_DATA_STUDENT';
export const CHANGE_SIGNUP_FORM = 'CHANGE_SIGNUP_FORM';
